name: Test Program
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: install dependencies
      run: pip install flake8
           pip install pytest

    # - name: run lint [flake8]
    #   run: flake8

    - name: run unit tests [pytest]
      run: pytest      


