name: Test Program
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: run linter[flake8]
        run: flake8 .

      - name: run unit tests [pytest]
        run: pytest      


